import React from 'react';
import {Modal,Button,Card,Row} from 'antd'

const TermsandCondition = ({setTermAndCondition}) => {
    const cancelbtnHandlar=()=>{
        setTermAndCondition(()=>false);
    }
    return (
        <div>
            <Card className="modal_theme modal-content offer animate__animated animate__fadeInUpBig" style={{textAlign:"justify",zIndex:"4",overflow:"scroll"}}>
            <Row>
            <label className="modalHeaderHeading" style={{margin:"3px 0 0 6px"}}>Terms and Conditions</label>
            <label className="modalCrox" onClick={cancelbtnHandlar} style={{float:"right",margin:"10px 13px 0 0",fontSize:"15px"}}>X</label>
            <hr style={{margin:"2px"}}/>
            </Row>
            <Card style={{padding:"15px"}}>
                <p>Please read the Terms and Conditions of this document carefully before accepting. By clicking on the "ACCEPT" button below, you are expressly agreeing to access the Equifax Credit Information Report and Credit Score (as defined in the Important Information Section below) (together referred as "Credit Information") and share a copy of the Credit Information with CreditMonitor in the "as is" format. Please click on the link below to read and understand the Important Information section below. ** This document is an electronic record in terms of the Information Technology Act, 2000 and Rules made there under, and the amended provisions pertaining to electronic records.</p>
                <label style={{color:"black"}}>INFORMATION IN RELATION TO ACCESS TO CREDIT INFORMATION THROUGH EQUIFAX Information Collection, Use, Confidentiality, No-Disclosure, Data Purging and Modification
</label>
            <p>CreditMonitor can only access your Credit Information as your authorized representative and shall use the Credit Information for limited end use purpose consisting of and in relation to the services proposed to be availed by you from us on the Website. We shall not aggregate, retain, store, copy, reproduce, republish, upload, post, tranxsit, sell or rent the Credit Information to any other person and the same cannot be copied or reproduced other than as agreed herein. We shall protect and keep confidential the Credit information both online and offline and use best in class security measures in line with applicable laws. The Credit Information shared by You, or received on your behalf shall be destroyed, purged, erased promptly upon the earlier of: (i) your written request to terminate this relationship with CreditMonitor (ii) the completion of provision of the Services by us to you.</p>
            <label style={{color:"black"}}>
            Modification of Terms of Service:
            </label>
            <p>
            CreditMonitor may change the terms and conditions of the Service upon which CreditMonitor will notify you of the changes. CreditMonitor may at its sole discretion from time to time offer you variety of features and facilities for the service. CreditMonitor however reserves its right to discontinue to offer such features and facilities for the service at anytime without prior notice. Governing Law and Jurisdiction The relationship between you and the Parties shall be governed by laws of India and all claims or disputes arising there from shall be subject to the exclusive jurisdiction of the courts of Mumbai.

            </p>
            <label style={{color:"black"}}>Defination <p>Capitalised terms used herein but not defined above shall have the following meanings: "Business Day" means a day (other than a public holiday) on which banks are open for general business in [Mumbai]. "Credit Information Report" means the credit information / scores / aggregates / variables or reports which shall be generated by Equifax; "Credit Score" means the score which shall be mentioned on the Credit Information Report which shall be computed by Equifax. "CICRA"" shall mean the Credit Information Companies (Regulation) Act, 2005 read with the Credit Information Companies Rules, 2006 and the Credit Information Companies Regulations, 2006, and shall include any other rules and regulations prescribed thereunder.


"Equifax is in the business of providing Credit Information Services to Consumers and Specified Users in accordance with the Credit Information Companies (Regulation) Act, 2005 read with the Rules and Regulations of 2006. Equifax helps people to check their credit report and credit score, and protect against identity theft."</p></label>

            <label style={{color:"black"}}>PLEASE READ THE ABOVE MENTIONED IMPORTANT INFORMATION AND CLICK ON "ACCEPT" FOLLOWED BY THE LINK BELOW TO COMPLETE THE AUTHORISATION PROCESS FOR SHARING OF YOUR CREDIT INFORMATION BY EQUIFAX WITH YOU AND CREDITMONITOR, IN ITS CAPACITY AS YOUR AUTHORISED REPRESENTATIVE. BY CLICKING "ACCEPT" YOU AGREE AND ACCEPT THE DISCLAIMERS AND TERMS AND CONDITIONS SET OUT HEREIN. THE TERMS AND CONDITIONS MENTIONED HEREIN MAY CHANGE IN ORDER TO COMPLY WITH GOVERNING LAWS OF THE COUNTRY AND THE CONSUMER SHALL BE BOUND TO ANY CHANGES TO THIS AGREEMENT</label>
            </Card>
            <hr style={{margin:'2px'}}/>
            <Row style={{marginBottom:"2px"}}>
            <Button onClick={cancelbtnHandlar} style={{float:"right",margin:"0 10px 10px 0"}}>Close</Button></Row>
        </Card>
        </div>
    );
};

export default TermsandCondition;